[package]
name = "delay"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
uuid = {version = "1.9", features = ["v4", "fast-rng"]}

tracing = "0.1"

[dev-dependencies]
tracing-test = "0.2"

# [[bench]]
# name = "simple"
# harness = false