[package]
name = "delay"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
uuid = {version = "1.7", features = ["v4", "fast-rng"]}

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "simple"
harness = false